# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_phone', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dimension_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimension_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimension_z', models.DecimalField(decimal_places=2, max_digits=5)),
                ('release_date', models.CharField(max_length=20)),
                ('market_rating', models.PositiveSmallIntegerField()),
                ('photo_video', models.PositiveSmallIntegerField()),
                ('play_media', models.PositiveSmallIntegerField()),
                ('communicate', models.PositiveSmallIntegerField()),
                ('gaming', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
