# Generated by Django 2.0 on 2017-12-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalphone',
            name='market_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
