# Generated by Django 2.0 on 2017-12-29 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20171228_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='phones')),
                ('front_image', models.ImageField(upload_to='phones')),
                ('back_image', models.ImageField(upload_to='phones')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.FinalPhone')),
            ],
        ),
    ]
