# Generated by Django 2.0 on 2017-12-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phonepics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonepics',
            name='phone',
        ),
        migrations.AddField(
            model_name='phonepics',
            name='phones',
            field=models.ForeignKey(blank=True, db_column='id_phone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.FinalPhone'),
        ),
    ]
