# Generated by Django 2.0 on 2017-12-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20171229_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhonePics',
            new_name='PhonePic',
        ),
    ]
