# Generated by Django 2.0 on 2017-12-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_remove_phonepic_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonepic',
            name='back_image',
            field=models.ImageField(upload_to='phones/media'),
        ),
        migrations.AlterField(
            model_name='phonepic',
            name='front_image',
            field=models.ImageField(upload_to='phones/media'),
        ),
    ]
