# Generated by Django 2.0 on 2017-12-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_phonepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonepic',
            name='phones',
        ),
        migrations.DeleteModel(
            name='PhonePic',
        ),
    ]
