# Generated by Django 2.0 on 2017-12-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0010_auto_20171231_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to='phones/media')),
                ('back_image', models.ImageField(upload_to='phones/media')),
                ('phones', models.ForeignKey(blank=True, db_column='id_phone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.FinalPhone')),
            ],
        ),
    ]
