# Generated by Django 2.0 on 2018-01-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0012_auto_20171231_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalphone',
            name='link',
            field=models.CharField(default=0, max_length=2083),
            preserve_default=False,
        ),
    ]
