# Generated by Django 2.0 on 2018-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0013_finalphone_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalphone',
            name='android',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalphone',
            name='dual_sim',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalphone',
            name='fingerprint',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalphone',
            name='ios',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalphone',
            name='nfc',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalphone',
            name='wd_resistant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
