# Generated by Django 2.0 on 2018-01-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0014_auto_20180106_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalphone',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='finalphone',
            name='nfc',
        ),
        migrations.AddField(
            model_name='finalphone',
            name='fast_charge',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
